import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export default function TermsPage() {
  return (
    <>

      <SiteHeader
        visibleSections={{
          hero: false,
          features: false,
          chapters: false,
          learning: false,
          audience: false,
          author: false,
          pricing: false,
          contact: false,
          subscribe: false,
        }}
      />
      <div class="container mx-auto">
        <h1>Termeni si Conditii</h1>
        <p><strong>TERMENII SI CONDITIILE</strong>&nbsp;generale se aplică tuturor vânzărilor de produse de către&nbsp;<strong>Societatea&nbsp; CLEAN CODE CULTURE S.R.L.</strong>&nbsp;prin intermediul magazinului online www.andreipata.ro</p>
        <p>IDENTITATEA PROFESIONISTULUI</p>
        <p><strong>ONE LOVE&nbsp;</strong>este denumirea comerciala (brand), a&nbsp;<strong>CLEAN CODE CULTURE S.R.L.,&nbsp;</strong>cu sediul social (adresa postala) in Drm. Fermei, nr.83E, ap.10, Popești-Leordeni, ILFOV inregistrata la Registrul Comertului ILFOV sub nr. J23/1903/20.03.2023 si cod unic de inregistrare 47847495, adresa electronica&nbsp;email andrei.pata@cleancodeculture.com<strong>,&nbsp;</strong>&nbsp;telefon +40 726 838 863.</p>
        <p>DEFINITII SI TERMENI</p>
        <p><strong>Site-ul –</strong>&nbsp;domeniul&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a> și subdomeniile acestuia sunt&nbsp; proprietatea CLEAN CODE CULTURE S.R.L.</p>
        <p><strong>Vânzător&nbsp;</strong>–&nbsp;<strong>CLEAN CODE CULTURE S.R.L.</strong></p>
        <p><strong>Cumpărător</strong>&nbsp;– persoană fizică de peste 18 ani/persoană juridică sau orice entitate juridică care își face un Cont în Site și efectuează o comandă.</p>
        <p><strong>Client</strong>&nbsp;– persoană fizică/persoană juridică care are sau obține acces la site-ul&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a> de pe orice dispozitiv de comunicare: electronic, telefonic, etc.</p>
        <p><strong>Utilizator</strong>&nbsp;– orice persoană fizică/juridică înregistrată pe site, care, prin finalizarea procesului de creare a Contului, a citit și și -a exprimat acordul cu privire la clauzele specifice site-ului din secțiunea Termeni și Condiții Generale.</p>
        <p><strong>Comandă</strong>&nbsp;– Un document electronic prin care Cumpărătorul transmite Vânzătorului, prin intermediul Site-ului, intenția de a achiziționa produse de pe site și prin care este permisă o formă de comunicare între Vânzător și Cumpărător.</p>
        <p><strong>Produse&nbsp;</strong>– Orice bun sau serviciu, inclusiv documentele și serviciile menționate în Comandă, care urmează să fie furnizate de către Vânzător, Cumpărătorului ca urmare a Contractului încheiat.</p>
        <p><strong>Campanie&nbsp;</strong>– Acțiunea de a expune în scop comercial, un număr finit de produse cu stoc limitat pentru o perioadă de timp stabilită de către Vânzător.</p>
        <p><strong>Contract</strong>&nbsp;– Un contract încheiat la distanță între Vânzător și Cumpărător.</p>
        <p><strong>Conținut&nbsp;</strong>– Informațiile care se pot vizualiza sau accesa prin utilizarea unui echipament electronic.</p>
        <p><strong>Newsletter&nbsp;</strong>– O formă de conținut cu un caracter de informare electronică, trimis prin e-mail sau SMS. În urma abonării, clientul primește informații asupra Bunurilor și Serviciilor și/sau a promoțiilor desfășurate de Vânzător la un anumit interval de timp.</p>
        <p><strong>Comunicari Comerciale</strong>&nbsp;– orice tip de mesaj trimis (cum ar fi: e-mail/SMS/telefonic/mobile push/webpush/etc.)&nbsp; continand informatii generale si tematice, informatii cu privire la produse similare sau complementare cu cele pe care le-ati achizitionat, informatii cu privire la oferte sau promotii, informatii referitoare la Bunuri si Servicii adaugate in sectiunea “Cont/Cosul meu” sau sectiunea&nbsp; “Cont/Favorite” precum si alte comunicari comerciale cum ar fi cercetari de piata si sondaje de opinie.</p>
        <p><strong>Tranzacție</strong>&nbsp;– Încasarea unei sume rezultată din vânzarea unui produs de către&nbsp;<strong>CLEAN CODE CULTURE S.R.L.</strong>., , Cumpărătorului, prin utilizarea serviciilor procesatorului, indiferent de modalitatea de livrare.</p>
        <p><strong>Specificatii</strong>&nbsp;– toate specificatiile si/sau descrierile Bunurilor si Serviciilor asa cum sunt precizate in descrierea acestora.</p>
        <p>Folosirea, incluzand vizitarea si cumpararea produselor de pe site-ul&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>, &nbsp;implica acceptarea termenilor si conditiilor ce vor fi detaliate in paragrafele urmatoare.</p>
        <p><strong>CLEAN CODE CULTURE S.R.L.</strong>&nbsp;furnizeaza serviciile care sunt subiectul termenilor si conditiilor de mai jos. Pentru folosirea in cele mai bune conditii a site-ului, care este administrat de&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>., se recomanda citirea cu atentie a acestor termeni si conditii.&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>. isi rezerva dreptul de a efectua orice modificari ale acestor prevederi, precum si orice modificari ale site-ului&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>, ale structurii acestuia sau orice alte modificari ce ar putea afecta site-ul, fara a fi necesara vreo notificare prealabila catre utilizatori in acest sens.</p>
        <p><strong>CLEAN CODE CULTURE S.R.L.</strong>. își rezerva dreptul de a face modificări ale acestor prevederi, fără o notificare prealabilă. Pagina “Termeni și condiții” conține întotdeauna cea mai recentă versiune a acestor prevederi.</p>
        <p><strong>CLEAN CODE CULTURE S.R.L.</strong>. nu va putea fi facuta responsabila pentru eventualele erori aparute pe site din orice cauza, inclusiv din cauza unor modificari, setari, up-grade-uri etc.</p>
        <p><strong>CLEAN CODE CULTURE S.R.L.</strong>&nbsp;nu raspunde de continutul, calitatea sau natura site-urilor la care se ajunge prin legaturi de pe site-ul&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>, indiferent de natura acestor legaturi. Pentru respectivele site-uri, raspunderea o poarta, integral, proprietarii site-urilor in cauza.</p>
        <p><a href="https://zaliano.ro/intrebari-frecvente/#instructiuni-de-folosire">CONDITII DE INTRETINERE SI UTILIZARE A PRODUSELOR</a></p>
        <p><strong>Documente contractuale.</strong></p>
        <p>Prin inregistrarea unei Comenzi pe Site, Cumparatorul este de acord cu forma de comunicare (telefonic sau e-mail) prin care Vanzatorul isi deruleaza operatiunile comerciale.</p>
        <p>Notificarea primita de catre Cumparator, dupa efectuarea Comenzii are rol de informare si nu reprezinta acceptarea Comenzii. Aceasta notificare se face electronic (e-mail) sau telefonic.</p>
        <p>Pentru motive justificate, Vanzatorul isi rezerva dreptul de a modifica cantitatea Bunurilor si/sau Serviciilor din Comanda. Daca modifica cantitatea de Bunuri si/sau Servicii din Comanda va anunta Cumparatorul la adresa de e-mail sau la numarul de telefon puse la dispozitia Vanzatorului la efectuarea Comenzii si va returna suma achitata</p>
        <p>Contractul se considera incheiat intre Vanzator si Cumparator in momentul primirii de catre Cumparator de la Vanzator, prin intermediul postei electronice si/sau SMS a notificarii de expediere a Comenzii.</p>
        <p>Documentul si informatiile puse la dispozitie de catre Vanzator pe Site vor sta la baza Contractului, in completarea acestuia fiind certificatul de garantie emis de catre Vanzator sau un furnizor al acestuia pentru Bunurile achizitionate.</p>
        <p><strong>Politica de vanzare online</strong></p>
        <p>Accesul in vederea efectuarii unei Comenzii ii este permis oricarui Utilizator/Cumparator.</p>
        <p>Pentru motive justificate <strong>CLEAN CODE CULTURE </strong>S.R.L.&nbsp; isi rezerva dreptul de a restrictiona accesul Utilizatorului/Cumparatorului in vederea efectuarii unei Comenzi si/sau la unele din modalitatile de plata acceptate, in cazul in care considera ca in baza conduitei sau a activitatii Utilizatorului/Cumparatorului pe Site, actiunile acestuia ar putea prejudicia in vreun fel <strong>CLEAN CODE CULTURE</strong> S.R.L. In oricare dintre aceste cazuri, Utilizatorul/Cumparatorul se poate adresa Departamentului de Relatii cu Clientii al <strong>CLEAN CODE CULTURE</strong> S.R.L., pentru a fi informat cu privire la motivele care au condus la aplicarea masurilor susmentionate.</p>
        <p>Comunicarea cu Vanzatorul se poate realiza prin interactiunea directa cu acesta, inclusiv prin suport online (Live Chat)&nbsp; sau prin adresele mentionate la sectiunea “contact” din Site. Vanzatorul are libertatea de a gestiona informatiile primite fara a fi nevoit sa aduca justificari pentru aceasta.</p>
        <p>In cazul unui volum de trafic neobisnuit de mare provenit din partea unei retele de internet, <strong>CLEAN CODE CULTURE</strong> S.R.L.&nbsp; isi rezerva dreptul de a cere Utilizatorilor/Cumparatorilor introducerea manuala a codurilor de validare de tip , in vedere protejarii informatiei din cadrul Site-ului.</p>
        <p><strong>CLEAN CODE CULTURE</strong> S.R.L.&nbsp; poate publica pe Site informatii despre Bunuri si/sau Servicii si/sau promotii practicate de catre acesta sau de catre oricare alt tert cu care <strong>CLEAN CODE CULTURE</strong> S.R.L.&nbsp; are incheiate contracte de parteneriat, intr-o anumita perioada de timp si in limita stocului disponibil.</p>
        <p>In cazul platilor online Vanzatorul nu este/nu poate fi facut responsabil pentru niciun alt cost suplimentar suportat de Cumparator, incluzand dar nelimitandu-se la comisioane de conversie valutara aplicate de catre banca emitenta a cardului acestuia, in cazul in care moneda de emitere a acestuia difera de RON. Responsabilitatea pentru aceasta actiune o poarta numai Cumparatorul.</p>
        <p>Toate informatiile folosite pentru descrierea Bunurilor si/sau a Serviciilor disponibile pe Site (imagini statice / dinamice / prezentari multimedia / etc.) nu reprezinta o obligatie contractuala din partea Vanzatorului, acestea fiind utilizate exclusiv cu titlu de prezentare.</p>
        <p>Dupa 14 (paisprezece) zile de la achizitionarea unui Bun sau Serviciu, Cumparatorului i se poate solicita inscrierea unui Review legat de Bunul sau Serviciul achizitionat. Solicitarea va fi transmisa catre adresa de email inscrisa de Cumparator in Cont. In acest fel, Cumparatorul contribuie la informarea altor posibili Utilizatori/ Clienti/ Cumparatori de pe Site si se implica activ in dezvoltarea de noi Servicii si in detalierea cat mai completa a caracteristicilor Bunurilor.</p>
        <p><strong>Cesionarea si subcontractarea.</strong></p>
        <p>Vanzatorul poate cesiona si/sau subcontracta o terta parte pentru Servicii ce tin de onorarea Comenzii, cu informarea Cumparatorului, nefiind necesar acordul acestuia. Vanzatorul va fi intotdeauna responsabil fata de Cumparator pentru toate obligatiile contractuale.</p>
        <p><strong>Comunicari electronice</strong></p>
        <p>Comunicarile comerciale prin posta electronica primite din partea&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>&nbsp;se realizeaza in cazul in care destinatarul si-a exprimat in prealabil consimtamantul expres pentru a primi asemenea comunicari. Destinatarul comunicarilor comerciale are dreptul de a-si revoca consimtamantul de a primi asemenea comunicari prin simpla dezabonare accesand link-ul potrivit de la sfarsitul fiecarui e-mail.</p>
        <p><strong>Exonerare de răspundere</strong></p>
        <p><strong>CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>&nbsp;nu garantează că site-ul&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>, serverele pe care este găzduit sau e-mailurile trimise de la&nbsp;<strong>CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>&nbsp;sunt fără viruși sau alte componente informatice cu potențial dăunător, că nu conține omisiuni, defecțiuni, întârzieri sau întreruperi în operare sau transmitere, căderi de linie sau alți factori similari.</p>
        <p><strong>Dreptul de proprietate intelectuala si industriala</strong></p>
        <p>Intregul continut al site-ului&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>, incluzand, enumerativ, texte, imagini, grafice, butoane, programe, elemente de grafica web, scripturi si orice alte date, este proprietatea&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L</strong>. si/sau a asociatilor sai si/sau a partenerilor sai si/sau a furnizorilor sai si este protejat conform Legii drepturilor de autor si legilor privind dreptul de proprietate intelectuala si industriala. Folosirea fara acordul scris al&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>&nbsp;a oricaror elemente enumerate mai sus se pedepseste conform legilor in vigoare.</p>
        <p>Continutul, astfel cum este definit in preambul, incluzand dar nelimitandu-se la logo-uri, reprezentari stilizate, simboluri comerciale, imagini statice, imagini dinamice, text si/sau continut multimedia prezentate pe Site, sunt proprietatea exclusiva a CLEAN CODE CULTURE S.R.L., acestuia fiindu-i rezervate toate drepturile obtinute in acest sens in mod direct sau indirect (prin licente de utilizare si/sau publicare).</p>
        <p>Clientului/Cumparatorului/Utilizatorului nu ii este permisa copierea, distribuirea, publicarea, transferul catre terte parti, modificarea si/sau altfel alterarea, utilizarea, legarea la, expunerea, includerea oricarui Continut in orice alt context decat cel original intentionat de CLEAN CODE CULTURE S.R.L. , includerea oricarui Continut in afara Site-ului, indepartarea insemnelor care semnifica dreptul de autor al CLEAN CODE CULTURE S.R.L. &nbsp;asupra Continutului precum si participarea la transferul, vanzarea, distributia unor materiale realizate prin reproducerea, modificarea sau afisarea Continutului, decat cu acordul scris expres al CLEAN CODE CULTURE S.R.L. .</p>
        <p>Orice Continut la care Clientul/Cumparatorul/Utilizatorul are si/sau obtine acces prin orice mijloc, se afla sub incidenta Documentului, in cazul in care Continutul nu este insotit de un acord de utilizare specific si valid incheiat intre CLEAN CODE CULTURE S.R.L. &nbsp;si acesta, si fara nicio garantie implicit sau expres formulata din partea CLEAN CODE CULTURE S.R.L. &nbsp;cu referire la acel Continut.</p>
        <p>Clientul/Cumparatorul/Utilizatorul poate copia, transfera si/sau utiliza Continut numai in scopuri personale sau non-comerciale, numai in cazul in care acestea nu intra in conflict cu prevederile Documentului.</p>
        <p>In cazul in care CLEAN CODE CULTURE S.R.L. &nbsp;confera Clientului/Cumparatorului/Utilizatorului dreptul de a utiliza sub forma descrisa intr-un acord de utilizare distinct, un anumit continut, la care Clientul/Cumparatorul/Utilizatorul are sau obtine acces in urma acestui acord, acest drept se extinde numai asupra acelui sau acelor continuturi definite in acord, numai pe perioada existentei acestuia sau acestor continuturi pe site sau a perioadei definite in acord, conform conditiilor definite, in cazul in care acestea exista si nu reprezinta un angajament contractual din partea CLEAN CODE CULTURE S.R.L. &nbsp;pentru respectivul Client/Cumparator/Utilizator sau oricare alt tert care are/obtine acces la acest continut transferat, prin orice mijloc si care ar putea fi sau este prejudiciat in orice mod de pe urma acestui continut, in timpul sau dupa expirarea acordului de utilizare.</p>
        <p>Niciun Continut transmis catre Client, Utilizator sau Cumparator, prin orice mijloc de comunicare (electronic, telefonic, etc) sau dobandit de acesta prin accesare, vizitare si/sau vizualizare nu constituie o obligatie contractuala din partea CLEAN CODE CULTURE S.R.L. &nbsp;si/sau al angajatului/prepusului CLEAN CODE CULTURE S.R.L. &nbsp;care a mijlocit transferul de Continut, in cazul in care aceasta exista, fata de respectivul continut.</p>
        <p>Este interzisa orice utilizare a Continutului in alte scopuri decat cele permise expres prin prezentul Document sau de acordul de utilizare care il insoteste, in cazul in care acesta exista.</p>
        <p>Toate programele folosite pe acest site sunt proprietatea&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>&nbsp;sau a furnizorilor sai de programe si sunt protejate de Legea drepturilor de autor.</p>
        <p>Orice eventuala incalcare a dreptului de autor sesizata pe site poate fi raportata pe adresa de email&nbsp;<a href="mailto:andrei.pata@cleancodeculture.com">andrei.pata@cleancodeculture.com</a></p>
        <p><strong>&nbsp;Accesul la site</strong></p>
        <p><strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>. garanteaza utilizatorului acces limitat, in interes personal, pe acest site si nu ii confera dreptul de a descarca sau de a modifica partial sau integral site-ul&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>, de a reproduce partial sau integral site-ul, de a copia, de a vinde/revinde sau de a exploata site-ul in orice alta maniera, in scopuri comerciale sau contrare intereselor&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>., fara acordul scris al acesteia.</p>
        <p><strong>Datele personale</strong></p>
        <p>Prin date cu caracter personal se inteleg orice informatii privind o persoana fizica identificata sau identificabila (“persoana vizata”); o persoana fizica identificabila este o persoana care poate fi identificata, direct sau indirect, in special prin referire la un element de identificare, cum ar fi un nume, un numar de identificare, date de localizare, un identificator online, sau la unul sau mai multe elemente specifice, proprii identitatii sale fizice, fiziologice, genetice, psihice, economice, culturale sau sociale;</p>
        <p>Datele personale ale utilizatorului vor putea fi folosite conform&nbsp;<a href="https://zaliano.ro/politica-de-prelucrare-a-datelor/">Politicii de prelucrare a datelor cu caracter personal.&nbsp;</a></p>
        <p><strong>Comentarii, comunicari si alte date/informatii</strong></p>
        <p>Cei care acceseaza/viziteaza site-ul&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>&nbsp;pot face comentarii si orice alte comunicari; pot sa transmita sugestii, idei, intrebari sau alte informatii, atata timp cat continutul acestora: nu este ilegal, obscen, amenintator, defaimator, nu tulbura in niciun fel viata privata a altor persoane, nu incalca drepturile de proprietate intelectuala, nu contine virusi, texte vizand diverse campanii de promovare, scrisori in lant, e-mailuri in masa sau orice alta forma de spam. Persoanele care vor utiliza o adresa falsa de e-mail sau vor transmite mesaje electronice sau orice alte comunicari in numele unei alte persoane fizice sau juridice sau in numele oricarei alte entitati vor fi sanctionate in conformitate cu legislatia in vigoare.</p>
        <p><strong>CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>. are dreptul (dar nu si obligatia) de a sterge orice astfel de continuturi identificate pe site.&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>&nbsp;nu va purta responsabilitatea si nici nu va putea fi obligata la nici un fel de despagubiri pentru orice fel de daune produse de asemenea comunicari.</p>
        <p>In cazul trimiterii sau afisarii unor materiale/documente, se considera ca utilizatorul confera&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>. si afiliatilor/asociatilor acesteia dreptul neexclusiv, nelimitat, gratuit, irevocabil si retransmisibil de a folosi, reproduce, modifica, adapta, publica, traduce, crea opere derivate, precum si dreptul de a distribui, de a prezenta aceste continuturi oriunde in lume, prin orice mijloc. Se garanteaza, de asemenea,&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>. si afiliatilor/asociatilor sai sau celor carora le retransmite dreptul de licenta dreptul de a utiliza numele pe care il asociati cu un astfel de continut. Utilizatorul garanteaza ca are toate drepturile asupra continutului pe care il afiseaza sau transmite pe site, prin orice modalitate, astfel incat, prin folosirea acestui continut, sa nu cauzeze prejudicii niciunei persoane.&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>. nu isi asuma nicio responsabilitate pentru continutul mesajelor/comunicarilor afisate/transmise de un utilizator prin intermediul site-ului&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>.</p>
        <p><strong>Securitatea informatiilor</strong></p>
        <p><strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>.. garanteaza securitatea si confidentialitatea datelor gazduite si transmise prin sistemul sau informatic.&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>. nu isi asuma insa responsabilitatea pentru pierderile de informatii cauzate de orice defectiuni sau erori ale softului cu care este conceput si gazduit site-ul. De asemenea,&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>. nu raspunde pentru defectiunile care pericliteaza securitatea serverului pe care este gazduit site-ul.</p>
        <p>Pentru platile cu cardul bancar, clientii isi vor introduce datele cardului exclusiv in platforma de plata securizata,&nbsp;<strong>&nbsp;CLEAN CODE CULTURE</strong> <strong>S.R.L.</strong>. SRL neavand acces la datele privind cardul.</p>
        <p>Pentru mai multe detalii&nbsp;<a href="https://zaliano.ro/politica-de-prelucrare-a-datelor/">citeste si Politica de Prelucrare a Datelor cu Caracter Personal.</a></p>
        <p><strong>Modalitatea de cumparare si livrare</strong></p>
        <p>Ofertele afisate pe site-ul <a href="https://www.andreipata.ro">www.andreipata.ro</a> valabile doar in cazul comenzilor on-line si sunt valabile in limita stocului disponibil.</p>
        <p>Preturile produselor includ TVA.</p>
        <p>Pretul fiecarui produs va fi cel mentionat pe site-ul <a href="https://www.andreipata.ro">www.andreipata.ro</a>, cu exceptia cazului in care exista o eroare evidenta. Cu toate ca avem grija sa ne asiguram ca toate preturile indicate pe site-ul nostru web sunt corecte, pot aparea erori. Cand pretul este in mod evident disproportionat fata de valoarea oricarui(/or) produs(e) comandate de dumneavoastra, va vom informa in cel mai scurt timp posibil pentru a va oferi optiunea de a reconfirma comanda la pretul corect sau de a o anula.</p>
        <p>Preturile pot fi revizuite in orice moment, insa (cu exceptiile mentionate mai sus), nicio schimbare nu va afecta vreo comanda a dumneavoastra care a fost inregistrata anterior modificarii preturilor.</p>
        <p>Dupa plasarea comenzii pe site, va primi un e-mail cu numarul de inregistrare a comenzii, la adresa de e-mail specificata in comanda.</p>
        <p>Confirmarea acceptarii comenzii&nbsp;se face de asemenea prin posta electronica, la adresa de e-mail a cumparatorului specificata in formularul de comanda, ceea ce reprezinta doar o confirmare a primirii comenzii, nu o confirmare efectiva a comenzii. Comenzile vor fi onorate in ordinea cronologica a primirii lor.</p>
        <p>Adaugarea unui Bun/Serviciu in cosul de cumparaturi, in lipsa finalizarii Comenzii, nu atrage dupa sine inregistrarea unei comenzi, implicit nici rezervarea automata a Bunului/Serviciului.</p>
        <p>Prin finalizarea Comenzii Cumparatorul consimte ca toate datele furnizate de acesta, necesare procesului de cumparare, sunt corecte, complete si adevarate la data plasarii Comenzii.</p>
        <p>Confirmarea acceptarii comenzii se face de asemenea prin posta electronica, la adresa de e-mail a cumparatorului specificata in formularul de comanda, dupa ce vanzatorul a verificat stocurile existente.</p>
        <p>In cazul in care&nbsp;<strong>produsul nu se afla in stocul depozitelor</strong>, consultantul de vanzari va comunica acest fapt Clientului/Cumparatorului in cel mai scurt timp, prin posta electronica. Daca in aceasta perioada imediata &nbsp;Clientul/Cumparatorul a achitat produsele din cos, CLEAN CODE CULTURE S.R.L. &nbsp;va rambursa sumele in termen de 7 zile de la data la care vanzatorul a comunicat consumatorului indisponibilitatea produsului.</p>
        <p><strong>CLEAN CODE CULTURE</strong> <strong>S.R.L</strong>&nbsp;nu garanteaza disponibilitatea produselor si nu poate fi trasa la raspundere in cazul in care articolul respectiv nu se afla in stocul furnizorilor.</p>
        <p>In conformitate cu art.8, alin.(9) din OUG nr. 34/2014&nbsp;privind drepturile consumatorilor in cadrul contractelor incheiate cu profesionistii, precum si pentru modificarea si completarea unor acte normative,&nbsp;momentul incheierii contractului la distanta il constituie momentul confirmarii de catre vanzator a acceptarii comenzii transmise de consumator.</p>
        <p>Produsul comandat se livreaza in termen de 2-5 zile de la data&nbsp;confirmarii de catre vanzator a acceptarii comenzii&nbsp;cumparatorului plasate pe site-ul&nbsp;<a href="http://www.comunicareimposibila.ro">www.comunicareimposibila.ro</a>, prin curierat rapid, intre zilele luni – sambata la adresa specificata de catre consumator in cadrul comenzii plasate pe site.</p>
        <p>Cu toate acestea, este posibil sa apara intarzieri din motive independente vanzatorului, ca de exemplu intarzierile cauzate de societatea de curierat rapid in perioada sarbatorilor de iarna, Paste, Black Friday etc., situatie in care vanzatorul va informa clientul cu privire la aceasta situatie si ii va oferi optiunea de a mentine comanda cu o noua data de livrare sau de a anula comanda cu rambursarea intregii sume achitate.</p>
        <p>Pentru mai multe detalii va rogam sa cititi&nbsp;<a href="https://zaliano.ro/politica-de-livrare/">politica de livrare</a>.</p>
        <p>Pentru fiecare comanda plasata pe &nbsp;<a href="http://www.comunicareimposibila.ro">www.comunicareimposibila.ro</a> se va percepe o&nbsp;<strong>taxa de ambalare&nbsp;</strong>in valoare de&nbsp;<strong>5 lei</strong>&nbsp;(cost necesar manipularii si ambalarii produselor comandate)&nbsp;si un&nbsp;<strong>cost de transport</strong>, ce difera in functie de modalitatea de livrare selectata de client in pagina de finalizare a comenzii:</p>
        <ul>
          <li>comenzile cu valoare totala mai mare sau egală cu 100 &nbsp;lei beneficiaza de&nbsp;<strong>livrare gratuita*</strong>, in&nbsp;<a href="http://chicville.ro/media/wysiwyg/Pdf-uri/Cargus.pdf">aria de acoperire a companiei de curierat</a>&nbsp;cu care colaboram</li>
          <li>pentru comenzile a caror valoare totala este mai mica de 100 de lei, se va aplica un cost de transport in valoare de&nbsp;<strong>10 lei&nbsp;</strong></li>
        </ul>
        <p><strong>Receptia produselor</strong></p>
        <p><strong>&nbsp;</strong>Intrucat comercializam produse fragile, clientul va verifica starea coletului iar, daca se va constata ca ambalajul este deteriorat, va deschide coletul in fata curierului pentru a verifica produsele si va solicita curierului intocmirea unui Proces-verbal de constatare in acest sens. In cazul expedierilor cu contact redus, daca se va constata ca ambalajul este deteriorat, clientul va reclama acest aspect imediat dupa primirea coletului, inainte de deschiderea acestuia.</p>
        <p>In caz de deteriorare a produselor, reclamatia insotita de poze ale coletului deteriorat vor fi transmise in termen de 2 zile pe e-mail catre&nbsp;<strong>&nbsp;CLEAN CODE CULTURE SRL</strong>., la adresa de email:&nbsp;andrei.pata@cleancodeculture.com Prin semnarea bonului de livrare de la curier, clientul admite primirea in conditii bune a coletului comandat, nu se admit reclamatii ulterioare. Site-ul&nbsp;<a href="http://www.comunicareimposibila.ro">www.comunicareimposibila.ro</a> &nbsp;pune la dispozitia clientilor sai optiunea de deschidere a coletului la livrare, in fata curierului, acest lucru avand rolul de a constata starea produselor comandate la livrare. In caz de deteriorare a produselor, se va intocmi impreuna cu curierul un Proces-verbal de constatare. Procesul-verbal de constatare va fi transmis pe e-mail catre&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>, in termen de 2 zile.</p>
        <p>Prezentul capitol se completeaza cu&nbsp;<a href="https://zaliano.ro/politica-de-retur/">Politica de retur</a>.</p>
        <p><strong>Politica de preturi</strong></p>
        <p><strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>. va putea desfasura orice campanie promotionala referitor la produsele afisate pe site, promotii ale caror conditii vor fi stabilite in intregime de catre&nbsp;<strong>&nbsp;CLEAN CODE CULTURE SRL</strong></p>
        <p><strong>Politica de solutionare a reclamatiilor</strong></p>
        <p><strong>CLEAN CODE CULTURE S.R.L.</strong>&nbsp;ofera posibilitatea Cumparatorului, in conformitate cu normele legale in domeniul protectiei consumatorului, de a inainta o reclamatie scrisa, ori de cate ori va considera ca drepturile sale au fost inculcate.</p>
        <p>Reclamatia trebuie inaintata/expediata, in forma scrisa, de catre cumparator in cel mult 30 de zile calendaristice de la data producerii evenimentului contestat, la adresa sediul social al societatii (Drm. Fermei, nr.83E, ap.10, Popești-Leordeni, ILFOV, Cod Postal 077160).</p>
        <p>Reclamatia va trebui sa contina obligatoriu urmatoarele elemente: numele, prenumele persoanei care adreseaza plangerea, datele de identificare ale acestuia, descrierea completa a reclamatiei, precum si data cand s-a produs si, daca este cazul, ora la care s-a produs, adresa completa si corecta la care se doreste primirea raspunsului, inclusiv adresa de posta electronica, data intocmirii reclamatiei si semnatura.</p>
        <p>Orice reclamatie expediata in termen si care va cuprinde toate elementele de mai sus, va fi solutionata in termen de 30 de zile calendaristice de la data primirii ei.&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>&nbsp;va raspunde reclamatiei adresate in scris, prin expediere postala cu confirmare de primire sau prin posta electronica, daca in cuprinsul reclamatiei clientul a optat pentru aceasta si a furnizat o adresa de e-mail, in acest sens.</p>
        <p><strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>&nbsp;nu garanteaza solutionarea favorabila a reclamatiei. In situatia in care cumparatorul nu va gasi solutia adoptata de societate ca fiind cea potrivita situatiei sale, se poate adresa instantelor de judecata competente de la sediul&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong></p>
        <p><strong>Limitele responsabilitatii</strong></p>
        <p>Continutul site-ului (texte, descrieri ale produselor, caracteristici tehnice, imagini, simboluri) a fost alcatuit in stransa colaborare cu reprezentantii in Romania ai marcilor prezentate pe site, astfel incat&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>. nu isi asuma responsabilitatea pentru descrierile produselor prezentate pe site in scopul comercializarii, acestea fiind corespunzatoare celor puse la dispozitia&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>. de catre reprezentantii fiecarei dintre aceste marci in parte. De asemenea, imaginile care sunt prezentate pe site sunt cu titlu de exemplu, produsele efectiv livrate putand diferi de acestea in ceea ce priveste culoarea, aspectul s.a.</p>
        <p>Produsele prezentate si vandute pe site-ul&nbsp;<a href="https://www.andreipata.ro">www.andreipata.ro</a>, sunt proprietatea&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong></p>
        <p><strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>. nu isi asuma responsabilitatea si nu poate fi facuta responsabila pentru orice pagube aparute prin folosirea in orice fel a produselor achizitionate prin intermediul acestui site, produse pentru care&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>. ofera garantie conforma legilor in vigoare si cu conditia ca aceste produse sa fie folosite conform indicatiilor tehnice.</p>
        <p>In cazul in care pretul unui produs a fost afisat gresit,&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>. isi rezerva dreptul de a anula livrarea respectivului produs, daca pretul este disproportionat in raport de valoarea produsului vandut, eroarea fiind evidenta. Vanzatorul va anunta clientul in cel mai scurt timp despre eroarea aparuta, si- i va returnarea sumele incasate cu titlu de plata, daca este cazul.</p>
        <p><strong>Serviciul impachetare cadou</strong></p>
        <p>Pot beneficia de acest serviciu doar produsele de mici dimensiuni, care pot fi impachetate in cutie cadou cu dimensiune de 20x20x25 cm.</p>
        <p><strong>Drept aplicabil. Litigii</strong></p>
        <p>Prin folosirea (vizitarea sau cumpararea produselor) site-ului, utilizatorul se declara de acord asupra faptului ca legile romane vor guverna Conditiile si Termenii de utilizare de mai sus si orice disputa de orice fel care ar putea sa apara intre utilizator si &nbsp;CLEAN CODE CULTURE S.R.L. In cazul unor eventuale conflicte intre &nbsp;CLEAN CODE CULTURE S.R.L. si clientii sai, se va incerca mai intai rezolvarea acestora pe cale amiabila. Daca rezolvarea pe cale amiabila nu va fi posibila, conflictul va fi solutionat in instanta competenta de la sediul vanzatorului.</p>
        <p><strong>Dispozitii finale</strong></p>
        <p>Daca oricare dintre clauzele de mai sus va fi gasita nula sau nevalida, indiferent de cauza, aceasta clauza nu va afecta valabilitatea celorlalte clauze. Odata cu lansarea comenzii, clientul accepta fara obiectiuni conditiile si termenii de utilizare, valoarea acestora fiind aceeasi cu un contract valabil incheiat.</p>
        <p>Principiile care definesc actiunile noastre zilnice sunt cuprinse in Codul de conduita, care reprezinta ansamblul de reguli care nu este impus prin legislatie sau dispozitii administrative si care defineste comportamentul societatii cu privire la practicile comerciale.</p>
        <p>Cumparatorul poate obtine o copie dupa Codul de conduita, printr-o cerere scrisa transmisa la sediul social al&nbsp;<strong>&nbsp;CLEAN CODE CULTURE S.R.L.</strong>, respectiv la adresa – Drm. Fermei, nr.83E, ap.10, Popești-Leordeni, ILFOV, Cod Postal 077160.</p>
        <p>&nbsp;</p>

      </div>

      <SiteFooter />
    </>
  )
}